Repository ACM-VIT/gitpositive, pull requests merged in 2021-10, with the labels that each got.

#8 Added Dark and Light Mode, Enhanced UI, Added Loading Dialog, Added validations for empty TextBox, Changed Fonts, Added Custom Cursor,
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/discord.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/acmvit/gitpositive/HomeScreen.kt
  app/src/main/java/org/acmvit/gitpositive/MainActivity.kt
  app/src/main/res/drawable/border.xml
  app/src/main/res/drawable/cursor.xml
  app/src/main/res/font/poppins.xml
  app/src/main/res/font/poppins_bold.xml
  app/src/main/res/font/poppins_light.xml
  app/src/main/res/font/poppins_medium.xml
  app/src/main/res/font/poppins_semibold.xml
  app/src/main/res/layout/activity_home_screen.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/loading_dialog.xml
  app/src/main/res/raw/loading.json
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/themes.xml
Labels: hactoberfest-accepted

#14 On screen orientation change, all ui elements are not visible #10
  app/src/main/res/layout/activity_main.xml
Labels: hactoberfest-accepted

#13 Added viewmodel support to handle thread handling and screen stuck issue
  app/build.gradle
  app/src/main/java/org/acmvit/gitpositive/MainActivity.kt
  app/src/main/java/org/acmvit/gitpositive/MainViewModel.kt
Labels: hactoberfest-accepted

#11 Fix status bar icon color on light background
  app/src/main/res/values/themes.xml
Labels: hactoberfest-accepted

#20 fix: issues with username box
  app/src/main/res/layout/activity_home_screen.xml
Labels: hactoberfest-accepted

#27 fix: Login Screen
  app/src/main/res/layout/activity_home_screen.xml
Labels: hacktoberfest-accepted

#30 fix: Navigation Bar Colour
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: hacktoberfest-accepted

#31 Infinite Loading Dialog bug
  app/src/main/java/org/acmvit/gitpositive/MainViewModel.kt
Labels: hacktoberfest-accepted

#32 Added Error Screen when Internet is not connected.
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/acmvit/gitpositive/HomeScreen.kt
  app/src/main/java/org/acmvit/gitpositive/MainActivity.kt
  app/src/main/java/org/acmvit/gitpositive/NetworkConnection.kt
  app/src/main/res/layout/activity_home_screen.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/raw/nointernet.json
Labels: hacktoberfest-accepted

#34 Splash Activity Added
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/acmvit/gitpositive/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/splash.json
Labels: hacktoberfest-accepted

#40 Created and added app icon using the colors mentioned in colors xml
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher2.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round2.xml
  app/src/main/res/mipmap-hdpi/ic_launcher2.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round2.png
  app/src/main/res/mipmap-mdpi/ic_launcher2.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round2.png
  app/src/main/res/mipmap-xhdpi/ic_launcher2.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round2.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher2.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round2.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher2.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round2.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: hacktoberfest, hacktoberfest-accepted

#47 about screen layout orientation changes
  .idea/misc.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_home_screen.xml
  app/src/main/res/values/strings.xml
Labels: hacktoberfest-accepted

#52 Added Bottom Sheet fragment showing followers and following.
  app/build.gradle
  app/src/main/java/org/acmvit/gitpositive/MainActivity.kt
  app/src/main/java/org/acmvit/gitpositive/adapters/FollowersAdapter.kt
  app/src/main/java/org/acmvit/gitpositive/adapters/FollowingAdapter.kt
  app/src/main/java/org/acmvit/gitpositive/models/Follower.kt
  app/src/main/java/org/acmvit/gitpositive/models/Following.kt
  app/src/main/res/drawable/bottom_sheet_bg.xml
  app/src/main/res/drawable/sheet_top.xml
  app/src/main/res/layout/bottom_followers.xml
  app/src/main/res/layout/bottom_following.xml
  app/src/main/res/layout/follower_following_layout.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: hacktoberfest-accepted

#58 Bug Fixed : Bottom Sheet Fragment of Followers & Following isn't displaying the last user.
  app/src/main/java/org/acmvit/gitpositive/MainActivity.kt
  app/src/main/res/layout/bottom_followers.xml
  app/src/main/res/layout/bottom_following.xml
Labels: hacktoberfest-accepted

#60 increased per page results from 30 to 100
  app/src/main/java/org/acmvit/gitpositive/ApiInterface.kt
  app/src/main/java/org/acmvit/gitpositive/MainActivity.kt
Labels: hacktoberfest-accepted
